### ISSUE TITLE
Documentation Improvement - Uninstall docker compose instructions

### ISSUE THREAD

**Issue by pgstath** [percona/percona-everest-backend#213]
In the Percona Everest uninstall page https://docs.percona.com/everest/install/uninstallEverest.html step 8 is:

`docker-compose -f quickstart.yml down`

instead of 
'docker compose -f quickstart.yml down'

**Comment by gen1us2k** [comment]
Thanks for the report. I'll handle it

**Comment by gen1us2k** [comment]
https://github.com/percona/everest-doc/pull/44 fixed it and it was merged. Closing it
